apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nginx
data:
  default.conf: |
    upstream backend {
      server backend-svc:8080;
    }

    server {
      listen 80 default_server;
      access_log  /var/log/nginx/nx.access.log; 
      error_log /var/log/nginx/nx.error.log; 

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      location /api { 
        # proxy_set_header X-Real-IP $remote_addr; 
        # proxy_set_header Host               $host; 
        # proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for; 
        # proxy_set_header X-Forwarded-Server $host; 
        add_header X-debug-message "backend /api" always;
        proxy_pass http://backend;
      }
    }
