apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nginx
data:
  default.conf: |
    server {
      listen 80 default_server;
      access_log  /var/log/nginx/nx.access.log; 
      error_log /var/log/nginx/nx.error.log; 

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }
    }
